[package]
name = "baseline-simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
rand = "0.9.2"
serde = "1.0.219"
serde_json = "1.0.143"
types = { path = "../types" }
